name: Deploy to GitHub Pages (static export)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Ensure npm
        run: |
          corepack enable
          corepack prepare npm@latest --activate

      - name: Install deps
        run: npm ci

      - name: Build & Export (static -> out/)
        run: |
          npm run build
          npx next export

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
